# Generated by Django 5.1.1 on 2024-09-08 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('M', 'Мужской'), ('F', 'Женский')], max_length=1)),
                ('family_status', models.CharField(choices=[('single', 'Одинокий/ая'), ('married', 'Женат/Замужем'), ('widowed', 'Вдова/Вдовец')], max_length=10)),
                ('height', models.PositiveIntegerField()),
                ('weight', models.PositiveIntegerField()),
                ('lifestyle', models.CharField(choices=[('no_activity', 'Почти нет активности'), ('low_activity', 'Слабая активность'), ('high_activity', 'Высокая активность'), ('extreme_activity', 'Экстремальная активность')], max_length=20)),
                ('sexual_activity', models.BooleanField()),
                ('medication_allergy', models.BooleanField()),
                ('medication_count', models.PositiveIntegerField()),
                ('medication_frequency', models.CharField(max_length=10)),
                ('smoking_frequency', models.CharField(max_length=10)),
                ('alcohol_frequency', models.CharField(max_length=10)),
            ],
        ),
    ]
